CREATE TABLE IF NOT EXISTS authorities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    authority VARCHAR(30) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_authorities (
    authority_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (authority_id, user_id),
    CONSTRAINT fk_user_authorities_authorities FOREIGN KEY (authority_id) REFERENCES authorities(id),
    CONSTRAINT fk_user_authorities_users FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX fk_user_authorities_users_idx ON user_authorities(user_id);
CREATE INDEX fk_user_authorities_authorities_idx ON user_authorities(authority_id);

INSERT INTO authorities (authority) VALUES ('ROLE_USER');
INSERT INTO authorities (authority) VALUES ('ROLE_ADMIN');

ALTER TABLE users ADD COLUMN username VARCHAR(40) UNIQUE NOT NULL;
ALTER TABLE users ADD COLUMN password VARCHAR(255) NOT NULL;

CREATE INDEX users_username_idx ON users(username);

CREATE INDEX transactions_user_id_idx ON transactions(user_id);